version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8001:80"
        volumes:
            - ./app:/src
            - ./env-config/site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7-fpm
        volumes:
            - ./app:/src
            - ./env-config/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    postgresql:
        image: postgres
        ports:
        - 5432:5432
