version: 2

services:
    web:
        image: nginx:latest
        ports:
            - "8001:80"
        volumes:
            - ./src:/src
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7-fpm
        volumes:
            - ./src:/src
            - ./config/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
